services:
  - type: web
    name: tripadvisor-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: TRIPADVISOR_API_KEY
        sync: false
      - key: FLASK_PORT
        value: 5000
